name: .NET Core

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --no-build -c Release dtc.csproj -o . -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}
      - name: Publish NuGet
        run: dotnet nuget push *.nupkg -s https://f.feedz.io/it-minds/tools/nuget/index.json -k ${{ secrets.FEEDZ_API_KEY }} --skip-duplicate -n 1
